apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-dotnet60-basic-4wgr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-dotnet60-basic-4wgr
    app.kubernetes.io/part-of: dotnet-component
  name: devfile-sample-dotnet60-basic-4wgr
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: devfile-dotnet-deploy
      app.kubernetes.io/instance: devfile-sample-dotnet60-basic-4wgr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: devfile-dotnet-deploy
        app.kubernetes.io/instance: devfile-sample-dotnet60-basic-4wgr
    spec:
      containers:
      - image: quay.io/rsoaresd_org/spi-demos-lsxq-tenant/dotnet-component/devfile-sample-dotnet60-basic-4wgr@sha256:52efbe5b0fb0fc789f4e5749e6289a459e0c9832adc3bd41a6432849d2e92ad9
        imagePullPolicy: Always
        name: main
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
